# Generated by Django 4.1 on 2023-09-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Date',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
